default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: "<%= ENV.fetch("RAILS_PG_USERNAME") %>"
  password: "<%= ENV.fetch("RAILS_PG_PASSWORD") %>"

development:
  <<: *default
  database: ruby_dev_test_1_development

test:
  <<: *default
  database: ruby_dev_test_1_test

production:
  <<: *default
  database: ruby_dev_test_1_production
